name: deploy-site-preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  image-test:
    runs-on: ubuntu-latest
    environment: pr-test
    steps:
      - name: get PreviewID
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "PreviewID=${github.event.number}" >> $GITHUB_ENV
          else
            echo "PreviewID=main" >> $GITHUB_ENV
          fi

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: install
        run: yarn

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: gen online screenshots
        run: yarn run test:screenshots --domain=https://pr-preview-${{ PreviewID }}--arco-design.netlify.app

      - name: upload screenshots to argos-cli
        run: npx @argos-ci/cli upload ./tests/__screenshots__
