name: deploy-site-preview
on:
 pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          
      - name: install
        run: yarn && cd site && yarn && cd ../
          
      - name: build-components
        run: yarn icon && yarn build:es && yarn build:css

      - name: build-site
        run: yarn build:site
      
      - name: netlify install
        run: yarn add netlify-cli -D

      - name: netlify deploy
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          PR_NUMBER: ${{ github.event.number }}
        run: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID  --dir=site/dist --alias=$PR_NUMBER
        
      - name: PR Comment
       # You may pin to the exact commit or the version.
       # uses: github-actions-up-and-running/pr-comment@f1f8ab2bf00dce6880a369ce08758a60c61d6c0b
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          # GITHUB_TOKEN secret
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Message to comment
          message: |
            [click to preview](https://$PR_NUMBER--arco-design.netlify.app)

    



    



