name: pr_preview
on:
  workflow_dispatch:

jobs:

  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: init
        run: npm run init


      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: build-site
        run: yarn build:site

      - name: list files
        run: ls

      - name: netlify
        run: yarn add netlify-cli -D

      - name: netlify deploy
        run: netlify deploy --dir=site/dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID

    



