name: pr_check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  component-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn run dependencies

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: run-icon
        run: yarn icon

      - name: build:cjs
        run: yarn build:cjs

      - name: build:es
        run: yarn build:es
            
      - name: Upload build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
         name: build_dist
         path: (icon|es|dist|lib)


  jest-test:
    runs-on: ubuntu-latest
    needs: component-build
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Download build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: build_dist
          # Destination path
          path: ./

      - name: mock-time
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Singapore'
          timezoneMacos: 'Asia/Singapore'
          timezoneWindows: 'Singapore Standard Time'

      - name: test:client
        run: yarn test:client

      - name: test:node
        run: yarn test:node

  screenshots-test:
    runs-on: ubuntu-latest
    needs: component-build
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Download build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: build_dist
          # Destination path
          path: ./
      
      - name: gen screenshots
        run: yarn run test:screenshots

      - name: ls
        run: ll ./tests


